version: '3.2'

services:
  postgres:
    image: postgres:10.3
    environment:
      POSTGRES_USER: ''
      POSTGRES_PASSWORD: ''
    ports:
      - '5432:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/data

  website:
    depends_on:
      - postgres
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
    env_file: .env
    command: bundle exec rails s -b '0.0.0.0'
